-- Tabla para las confirmaciones de la invitación de María José
create table if not exists public.confirmaciones_xv (
  id bigint generated by default as identity primary key,
  nombre text not null,
  asistencia boolean not null,
  acompanantes integer not null default 0 check (acompanantes between 0 and 4),
  creado_en timestamptz not null default now()
);

-- Seguridad: los invitados pueden registrar una respuesta, pero NO pueden leer la tabla desde la invitación pública.
alter table public.confirmaciones_xv enable row level security;

drop policy if exists "Permitir registrar confirmaciones" on public.confirmaciones_xv;
create policy "Permitir registrar confirmaciones"
on public.confirmaciones_xv
for insert
to anon
with check (
  char_length(trim(nombre)) between 2 and 120
  and acompanantes between 0 and 4
);

-- No creamos policy SELECT pública.
-- Para consultar los asistentes, entra al Table Editor de Supabase.
